# inp_num1=(input("Enter the Number"))
# inp_num2=(input("Enter the Number"))
# print(inp_num1+inp_num2)
# print(type(inp_num1))
# print(type(inp_num2))
# con_str_num1=int(inp_num1)
# con_str_num2=int(inp_num2)
# print(con_str_num1+con_str_num2)

inp_num=(input("Enter the two digit Number"))
print(type(inp_num))
con_str_num=int(inp_num[0])
con_str_num1=int(inp_num[1])
print(con_str_num+con_str_num1)