mystr="Akshay is good boy"
print(len(mystr))
print(mystr[0:2]) #It exclude the last index
print(mystr[0:18])
print(mystr[:6])
print(mystr[0:])
print(mystr[0:18:2])
print(mystr[:])
print(mystr[::])
print(mystr[-4:-2])
print(mystr[::-1])
#alnum - ultra numeric number -- Boolean (True , False)
print(mystr.isalnum())
str="akshay,is learning python"
print(str.isalnum())
print(str.endswith("learning"))
print(str.endswith("python"))
print(str.count("a"))
print(mystr.count("o"))
print(str.capitalize())
print(str.find("is"))
print(str.upper())
print(str.replace("python" , "basicpython"))
print(str.split(","))